feast/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('', include('reservation.urls', namespace='reservation')),
    path('accounts/', include('allauth.urls')),
]

home/urls.py
from django.urls import path
from home.views import home

app_name = 'home'


urlpatterns = [
    path('', home.as_view(), name='home'),
]

reservation/urls.py
from django.urls import path
from . import views

app_name = 'reservation'

urlpatterns = [
    path('reserve_table/', views.reserve_table, name='reserve_table'),
    path('myBooking_list/', views.myBooking_list, name='myBooking_list'), 
    path('update_bookings/<booking_id>', views.updateBookings, name='update_bookings'),
    path('delete_booking/<booking_id>', views.deleteBooking, name='delete_booking'),
]

home/models.py
from django.db import models

# Create your models here.

reservation/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from django.core.validators import RegexValidator


# Create your models here.
class Table(models.Model):

    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, unique=True)
    guest = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user", null=True)

    def __str__(self):
        return self.name

reservation/forms.py
from django import forms
from .models import Table
from django.db.models import IntegerField, Model

from datetime import datetime
from django.core.validators import RegexValidator
from django.core.validators import MaxValueValidator, MinValueValidator


class bookingForm(forms.ModelForm):

    # Validations
    name = forms.CharField(
        label='Full Name', min_length=3, max_length=50,
        validators=[RegexValidator(regex=r'^[a-zA-ZÀ-ÿ\s]*$',
        message='Only letters are allowed')],
        widget=forms.TextInput(
            attrs={'placeholder': 'John Dave'})
    )
    email = forms.EmailField(
        label='Email address', min_length=8, max_length=50,
        validators=[RegexValidator(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$',
        message='Put a valid email address!')],
        widget=forms.TextInput(
            attrs={'placeholder': 'email@gmail.com'})
    )
    guest = forms.IntegerField(
        label='Guests',
        validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ],
        # help_text ="max number of guests you can invite is 10.",
        widget=forms.TextInput(
            attrs={'placeholder': 'Number of Guests?'}),
    )
    date = forms.DateField(widget=forms.DateInput(
        attrs={'type': 'date', 'min': datetime.now().date()}))
    time = forms.TimeField(widget=forms.TimeInput(attrs={'type': 'time'}))
    
    class Meta:
        model = Table
        fields = (
            'name',
            'email',
            'guest',
            'date',
            'time')
            

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


class home(TemplateView):
    '''
    this will view home page
    '''
    template_name = 'home/index.html'

reservation/views.py
from .models import *
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .forms import bookingForm
from reservation.models import Table


# Create your views here.
def reserve_table(request):
    '''
    this function will show reservation form
    if the user is registered and then will save it.
    for unregistered user, a message will be shown for sign in
    '''
    form = bookingForm()
    if request.method == 'POST':
        form = bookingForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            form = bookingForm()
            messages.success(request, "Booking succesful")
            return redirect('/myBooking_list')
        else:
            form = bookingForm()
            return render(request, 'reservation/reservation.html', {'form': form})
    context = {'form': form}
    return render(request, 'reservation/reservation.html', context)


@login_required
def myBooking_list(request):
    '''
    This function will show the reservation of the
    currently logged-in user if she is logged in
    otherwise sign-in page will be shown
    '''
    # if request.user.is_authenticated:
    bookings = Table.objects.filter(user=request.user)
    context = {'bookings': bookings}
    return render(request, "reservation/myBookings.html", context)


def updateBookings(request, booking_id):
    '''
    this function will edit/update the bookings of the user
    '''
    edit = Table.objects.get(id=booking_id)
    form = bookingForm(instance=edit)
    if request.method == 'POST':
        form = bookingForm(request.POST, instance=edit)
        if form.is_valid():
            form.save()
            form = bookingForm()
            return redirect('/myBooking_list')
            messages.success(request, "Booking succesful")
    return render(request, "reservation/edit_booking.html", {'form': form})


def deleteBooking(request, booking_id):
    '''
    this function will delete the user's booking from bookings list
    then will reconfirm deletion, after that will redirect the user
    to bookings list
    '''
    booking = Table.objects.get(id=booking_id)
    if request.method == "POST":
        booking.delete()
        return redirect('/myBooking_list')
    return render(request, "reservation/delete_booking.html", {'booking': booking})

reservation/templates/reservation/delete_booking.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

 <div class="container-fluid d-flex justify-content-center align-items-center" style="height: 80vh;">
    <div class="card text-center" id="Card">
        <div class="card-body p-4 ">
            <form action="/delete_booking/{{ booking.id }}" method="post">
                {% csrf_token %}
                <h4 class="card-title">Are you sure you want to cancel your booking?</h4>
                <h6 class="card-text m-3">Name: {{ booking.name }}</h6>
                <h6 class="card-text m-3">Date: {{ booking.date }}</h6>
                <h6 class="card-text m-3">Time: {{ booking.time }}</h6>
                <a href="/myBooking_list" class="btn btn-outline-success">NO</a>
                <input type="submit" class="btn btn-outline-danger"  name="YES" value="YES">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

reservation/templates/reservation/edit_booking.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}


{% block content %}

{% for msg in messages %}
  {{ msg }}
{% endfor %}

<!-- form -->
<div class="row justify-content-center g-0 mt-2 text-center">   
  <div id="Card" class="col-11 col-md-6 col-lg-5 col-xl-4 card-welcome border border-dark border-2 rounded-4 justify-content-center">
    <form method="post">
      <h4 class="pb-1 pt-2">Edit your booking</h4>
      <hr>
      {% csrf_token %}
      {{form.as_p}}


      <button type="submit" class="btn btn-outline-dark m-3">Done</button>

    </form>
  </div>
</div>

{% endblock content %}

reservation/templates/reservation/myBookings.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if not request.user.is_authenticated %}
<div class="container-fluid d-flex justify-content-center align-items-center" style="height: 80vh;">
  <div class="card text-center" id="Card">
    <div class="card-body p-4 text-white">
      <h4 class="card-title">Please Login First</h4>
      <h6 class="card-subtitle m-3">You can't see your booking list without login!</h6>
      <a href="{% url 'account_login' %}" class="btn btn-outline-dark">Go to Login Page</a>
    </div>
  </div>
</div>

{% else %}
<div class="container-fluid mb-3 p-1">
  {% if request.user.is_authenticated %}
  <h2 class="text-center pt-3"> My Bookings</h2> 
  <hr class="border border-danger border-2 opacity-40">
  <div id="table-scroll" class="table-responsive text-center h-100">
    <table class="table table-hover table-bordered border border-3">
      <thead class="fixed-thead table-dark">
          <tr>
            <th class="th-header" scope="col">Name</th>
            <th class="th-header" scope="col">Guest</th>
            <th class="th-header" scope="col">Date</th>
            <th class="th-header" scope="col">Time</th>
            <th class="th-header" scope="col"></th>
          </tr>
      </thead>
      <tbody>
          {% for booking in bookings %}
        <tr>     
          <td> {{booking.name}} </td>
          <td> {{booking.guest}} </td>
          <td> {{booking.date}} </td>
          <td> {{booking.time}} </td>
          <td>
            <a href="/update_bookings/{{ booking.id }}" class="text-decoration-none"> 
              <button class="btn btn-sm btn-primary edit-btn"> Edit </button>
            </a>
            <a href="/delete_booking/{{ booking.id }}" class="text-decoration-none"> 
              <button class="btn btn-sm btn-danger"> Delete </button>
            </a> 
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

reservation/templates/reservation/reservation.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block content %}

  <!-- toast message -->
    {% for msg in messages %}
      {{ msg }}
    {% endfor %}


  {% if not user.is_authenticated %}
  <div class="container-fluid d-flex justify-content-center align-items-center" style="height: 80vh;">
      <div class="card text-center" id="Card">
        <div class="card-body p-4 text-white">
          <h4 class="card-title">Please Login First</h4>
          <h6 class="card-subtitle m-3">You can't reserve a table without login!</h6>
          <a href="{% url 'account_login' %}" class="btn btn-outline-dark">Go to Login Page</a>
        </div>
      </div>
  </div>
  {% else %}
    <!-- form -->
  <section id="reservation" class="container m-1">
    <div class="row justify-content-center g-0 mb-5 text-center">
      
      <div id="Card" class="col-11 col-md-6 col-lg-5 col-xl-4 p-0 card-welcome border border-dark border-2 rounded-4 justify-content-center">
        <form action="" method="post" class="container p-4">
          <h4 class="pb-1">book a table </h4>
          <hr>
          {% csrf_token %}
          {{form|crispy}}
          
            <button type="submit" class="btn btn-outline-success m-3">Book</button>
        
        </form>
      </div>
    </div>  
  </section>
    
`{% endif %} 

{% endblock  %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Feast, restaurant, online booking">
    <meta name="description" content="an online booking restaurant">
    
    <!-- CSS Link -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Bootstrap CSS Link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- fontawsome Link -->
    <script src="https://kit.fontawesome.com/1f5f6187a8.js" crossorigin="anonymous"></script>
    
    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo.png' %}">
    
    <title>FEAST</title>
</head>
<body>
  <header>
    <!----- NAVBAR ----->
    <nav class="navbar navbar-dark shadow-lg p-3" style="background-color: #e47968;">
      <div class="container-fluid">
        <button class="navbar-toggler btn btn-outline-dark" type="button" id="OpenMenu">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">FEAST</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link" id="nav-list" href="{% url 'home:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" id="nav-list" href="{% url 'home:home' %}#about">About Us</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="nav-list" href="{% url 'home:home' %}#menu">Menu</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="nav-list" href="{% url 'reservation:myBooking_list' %}">My Bookings</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" id="nav-list" href="{% url 'reservation:reserve_table' %}">Reservation</a>
              </li>
            </ul>
          </div>
        </div>
        <!-- LOGO Name -->
        <a class="navbar-brand mx-auto">FEAST</a>

        <div class="mx-2">
          {% if user.is_authenticated %}
          
          <button class="btn btn-outline-dark">
              <a class="text-decoration-none text-white" href="{% url 'account_logout' %}">Logout</a>
          </button>
          {% else %}
          <button type="button" class="mx-1 btn btn-outline-dark">
            <a class="text-decoration-none text-white" href="{% url 'account_login' %}"> Login</a> </button>
          <button type="button" class="btn btn-outline-dark">
            <a class="text-decoration-none text-white" href="{% url 'account_signup' %}">Register</a> </button>
          {% endif %}
        </div>
      </div>
    </nav>
    <!-- End Navbar -->
  </header>

<!-- toast message -->
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% for message in messages %}
            <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
                {{ message | safe }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endfor %}
        </div>
    </div>
</div>



  <body class="flex-shrink-0 main-bg">
    {% block content %}
      <!-- Content Goes here -->
    {% endblock content %}
  </body>


  
<!-- Footer -->
  <footer class=" bg-dark text-center text-white fixed-bottom">
    <div class="row pb-0">
      <!-- social media -->
      <div class="col">
        <a class="btn btn-outline-light btn-floating m-1" href="https://www.facebook.com/" role="button">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/" role="button">
          <i class="fab fa-twitter"></i>
        </a>
        <a class="btn btn-outline-light btn-floating m-1" href="https://www.instagram.com/" role="button">
          <i class="fab fa-instagram"></i>
        </a>
          </div>
      <div class="col justify-content-end">
        <p>© 2023 Copyright</p> 
      </div>
    </div>
  </footer> 
<!-- End Footer -->
  

    <!-- Bootstrap JS link -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
  <!-- JS -->
  <script src="{% static 'js/script.js' %}"></script>
  
</body>
</html>